#!/usr/bin/env bash

git_revision=$(git rev-parse --short HEAD)

docker build \
  --build-arg GIT_COMMIT=$git_revision \
  . \
  -t benricheson101/csc-go-laundry-discord \
  -t ghcr.io/benricheson101/csc-go-laundry-discord
